### PR TITLE
Completed dragmap workflow

### PR DESCRIPTION
**Pull request by muna-anm**
This update fixes the regression tests.

Unfortunately I pushed directly to main originally. But I would appreciate feedback for the other parts of the workflow too!

### CODE REVIEW

**Comment by bibilujan** [comment]
This looks good! 
I wonder if we want to decrease the memory and increase the timeout, lets discuss what the requirements have been so far. With this workflow, for large inputs (eg. novaSeq), we would run it in 10+ chunks, if jobmemory is set to 50GB each job would get 50GB.

**Comment by bibilujan** [comment]
It does look like it will be safer to set the default memory high. We can do some testing and come back to it.
Can you update the timeout to be higher, maybe 96h.

**Comment by muna-anm** [comment]
> It does look like it will be safer to set the default memory high. We can do some testing and come back to it. Can you update the timeout to be higher, maybe 96h.

Yes, I think it might be safer to have the default memory 50GB or higher. I tried to run the NovaSeq data (20 chunks) again with 32-40GB  and the jobs were killed. I'm running it again with 45 GB, and I'll update you if it succeeds. But, since one of the MiSeq samples I was testing used around 48GB, I think it'll be best to put the default at 50 or higher.

Update: the NovaSeq data can successfully run with 45GB

**Review by bibilujan — APPROVED** [review]
Great job putting this workflow together!

**Review by lheisler — CHANGES_REQUESTED** [review]
this is organized to pull in the bwamem workflow, the purpose of this being is to make use of some of the pre/post processing functions.  While the general organization of the workflow should be similar to bwa (eg chunking), i don't think it should necessarily be dependent on that workflow in anyway (as is implied with the pull).


i think this should be a distinct workflow, copying over logic/functions as needed, which can develop independently in the future.

**Comment by lheisler** [comment]
Readgroups are handled very differently between bwa (where it is a single command line parameter) and dragen (which is limited, and we are depending on picard addorremove 

the workflow seems to take as input the same string that is sent to bwa, which is constructed specifically for bwa and has all that complexity (multiple tabs etc).
input instead should be simpler, i suggest a comma separate list of key value pairs (eg SM=sample,LB=library), which can be parsed and converted to the individual arguments.  It should also check for invalid tags, and either ignore or better to fail.   Olives will have to create this information appropriate to the workflow

**Comment by lheisler** [comment]
the bam index is currently from an indexing function in the bwaMem workflow, probably either samtools or picard to generate the index

addOrReplacereadgroups, which is the final step, can be given a --CREATE_INDEX argument, this would probably be more efficient and not require a distinct task, assuming that readgroup information is a requirement of the workflow, which i think it should be (if readgroup is not known, than can put in dummy values)

**Review by lheisler — APPROVED** [review]
Looks good, the changes i had suggested had been implemented

**Pull request merged**
